package cn.org.meteor.comp.mapper.generate;

import cn.org.meteor.comp.po.generate.UserCredenceInfo;
import cn.org.meteor.comp.po.generate.UserCredenceInfoExample;

import java.util.List;

public interface UserCredenceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    long countByExample(UserCredenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int deleteByExample(UserCredenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uciFlowno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int insert(UserCredenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int insertSelective(UserCredenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    List<UserCredenceInfo> selectByExample(UserCredenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    UserCredenceInfo selectByPrimaryKey(String uciFlowno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(UserCredenceInfo record, UserCredenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int updateByExample(UserCredenceInfo record,UserCredenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserCredenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserCredenceInfo record);
}