package cn.org.meteor.comp.po.generate;

import java.util.ArrayList;
import java.util.List;

public class UserCredenceInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public UserCredenceInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUciFlownoIsNull() {
            addCriterion("UCI_FLOWNO is null");
            return (Criteria) this;
        }

        public Criteria andUciFlownoIsNotNull() {
            addCriterion("UCI_FLOWNO is not null");
            return (Criteria) this;
        }

        public Criteria andUciFlownoEqualTo(String value) {
            addCriterion("UCI_FLOWNO =", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoNotEqualTo(String value) {
            addCriterion("UCI_FLOWNO <>", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoGreaterThan(String value) {
            addCriterion("UCI_FLOWNO >", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoGreaterThanOrEqualTo(String value) {
            addCriterion("UCI_FLOWNO >=", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoLessThan(String value) {
            addCriterion("UCI_FLOWNO <", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoLessThanOrEqualTo(String value) {
            addCriterion("UCI_FLOWNO <=", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoLike(String value) {
            addCriterion("UCI_FLOWNO like", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoNotLike(String value) {
            addCriterion("UCI_FLOWNO not like", value, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoIn(List<String> values) {
            addCriterion("UCI_FLOWNO in", values, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoNotIn(List<String> values) {
            addCriterion("UCI_FLOWNO not in", values, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoBetween(String value1, String value2) {
            addCriterion("UCI_FLOWNO between", value1, value2, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUciFlownoNotBetween(String value1, String value2) {
            addCriterion("UCI_FLOWNO not between", value1, value2, "uciFlowno");
            return (Criteria) this;
        }

        public Criteria andUniqueidIsNull() {
            addCriterion("UNIQUEID is null");
            return (Criteria) this;
        }

        public Criteria andUniqueidIsNotNull() {
            addCriterion("UNIQUEID is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueidEqualTo(String value) {
            addCriterion("UNIQUEID =", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotEqualTo(String value) {
            addCriterion("UNIQUEID <>", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidGreaterThan(String value) {
            addCriterion("UNIQUEID >", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidGreaterThanOrEqualTo(String value) {
            addCriterion("UNIQUEID >=", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidLessThan(String value) {
            addCriterion("UNIQUEID <", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidLessThanOrEqualTo(String value) {
            addCriterion("UNIQUEID <=", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidLike(String value) {
            addCriterion("UNIQUEID like", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotLike(String value) {
            addCriterion("UNIQUEID not like", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidIn(List<String> values) {
            addCriterion("UNIQUEID in", values, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotIn(List<String> values) {
            addCriterion("UNIQUEID not in", values, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidBetween(String value1, String value2) {
            addCriterion("UNIQUEID between", value1, value2, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotBetween(String value1, String value2) {
            addCriterion("UNIQUEID not between", value1, value2, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("LOGIN_NAME =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("LOGIN_NAME <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("LOGIN_NAME >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("LOGIN_NAME <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("LOGIN_NAME like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("LOGIN_NAME not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("LOGIN_NAME in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("LOGIN_NAME not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andCredenceClassIsNull() {
            addCriterion("CREDENCE_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andCredenceClassIsNotNull() {
            addCriterion("CREDENCE_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andCredenceClassEqualTo(String value) {
            addCriterion("CREDENCE_CLASS =", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassNotEqualTo(String value) {
            addCriterion("CREDENCE_CLASS <>", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassGreaterThan(String value) {
            addCriterion("CREDENCE_CLASS >", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassGreaterThanOrEqualTo(String value) {
            addCriterion("CREDENCE_CLASS >=", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassLessThan(String value) {
            addCriterion("CREDENCE_CLASS <", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassLessThanOrEqualTo(String value) {
            addCriterion("CREDENCE_CLASS <=", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassLike(String value) {
            addCriterion("CREDENCE_CLASS like", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassNotLike(String value) {
            addCriterion("CREDENCE_CLASS not like", value, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassIn(List<String> values) {
            addCriterion("CREDENCE_CLASS in", values, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassNotIn(List<String> values) {
            addCriterion("CREDENCE_CLASS not in", values, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassBetween(String value1, String value2) {
            addCriterion("CREDENCE_CLASS between", value1, value2, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceClassNotBetween(String value1, String value2) {
            addCriterion("CREDENCE_CLASS not between", value1, value2, "credenceClass");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendIsNull() {
            addCriterion("CREDENCE_APPEND is null");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendIsNotNull() {
            addCriterion("CREDENCE_APPEND is not null");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendEqualTo(String value) {
            addCriterion("CREDENCE_APPEND =", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendNotEqualTo(String value) {
            addCriterion("CREDENCE_APPEND <>", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendGreaterThan(String value) {
            addCriterion("CREDENCE_APPEND >", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendGreaterThanOrEqualTo(String value) {
            addCriterion("CREDENCE_APPEND >=", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendLessThan(String value) {
            addCriterion("CREDENCE_APPEND <", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendLessThanOrEqualTo(String value) {
            addCriterion("CREDENCE_APPEND <=", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendLike(String value) {
            addCriterion("CREDENCE_APPEND like", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendNotLike(String value) {
            addCriterion("CREDENCE_APPEND not like", value, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendIn(List<String> values) {
            addCriterion("CREDENCE_APPEND in", values, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendNotIn(List<String> values) {
            addCriterion("CREDENCE_APPEND not in", values, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendBetween(String value1, String value2) {
            addCriterion("CREDENCE_APPEND between", value1, value2, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceAppendNotBetween(String value1, String value2) {
            addCriterion("CREDENCE_APPEND not between", value1, value2, "credenceAppend");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusIsNull() {
            addCriterion("CREDENCE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusIsNotNull() {
            addCriterion("CREDENCE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusEqualTo(String value) {
            addCriterion("CREDENCE_STATUS =", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusNotEqualTo(String value) {
            addCriterion("CREDENCE_STATUS <>", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusGreaterThan(String value) {
            addCriterion("CREDENCE_STATUS >", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusGreaterThanOrEqualTo(String value) {
            addCriterion("CREDENCE_STATUS >=", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusLessThan(String value) {
            addCriterion("CREDENCE_STATUS <", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusLessThanOrEqualTo(String value) {
            addCriterion("CREDENCE_STATUS <=", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusLike(String value) {
            addCriterion("CREDENCE_STATUS like", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusNotLike(String value) {
            addCriterion("CREDENCE_STATUS not like", value, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusIn(List<String> values) {
            addCriterion("CREDENCE_STATUS in", values, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusNotIn(List<String> values) {
            addCriterion("CREDENCE_STATUS not in", values, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusBetween(String value1, String value2) {
            addCriterion("CREDENCE_STATUS between", value1, value2, "credenceStatus");
            return (Criteria) this;
        }

        public Criteria andCredenceStatusNotBetween(String value1, String value2) {
            addCriterion("CREDENCE_STATUS not between", value1, value2, "credenceStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_credence_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}