package cn.org.meteor.comp.po.generate;

import java.io.Serializable;

public class UserCredenceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credence_info.UCI_FLOWNO
     *
     * @mbg.generated
     */
    private String uciFlowno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credence_info.UNIQUEID
     *
     * @mbg.generated
     */
    private String uniqueid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credence_info.LOGIN_NAME
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credence_info.CREDENCE_CLASS
     *
     * @mbg.generated
     */
    private String credenceClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credence_info.CREDENCE_APPEND
     *
     * @mbg.generated
     */
    private String credenceAppend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credence_info.CREDENCE_STATUS
     *
     * @mbg.generated
     */
    private String credenceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credence_info.UCI_FLOWNO
     *
     * @return the value of user_credence_info.UCI_FLOWNO
     *
     * @mbg.generated
     */
    public String getUciFlowno() {
        return uciFlowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credence_info.UCI_FLOWNO
     *
     * @param uciFlowno the value for user_credence_info.UCI_FLOWNO
     *
     * @mbg.generated
     */
    public void setUciFlowno(String uciFlowno) {
        this.uciFlowno = uciFlowno == null ? null : uciFlowno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credence_info.UNIQUEID
     *
     * @return the value of user_credence_info.UNIQUEID
     *
     * @mbg.generated
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credence_info.UNIQUEID
     *
     * @param uniqueid the value for user_credence_info.UNIQUEID
     *
     * @mbg.generated
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid == null ? null : uniqueid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credence_info.LOGIN_NAME
     *
     * @return the value of user_credence_info.LOGIN_NAME
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credence_info.LOGIN_NAME
     *
     * @param loginName the value for user_credence_info.LOGIN_NAME
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credence_info.CREDENCE_CLASS
     *
     * @return the value of user_credence_info.CREDENCE_CLASS
     *
     * @mbg.generated
     */
    public String getCredenceClass() {
        return credenceClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credence_info.CREDENCE_CLASS
     *
     * @param credenceClass the value for user_credence_info.CREDENCE_CLASS
     *
     * @mbg.generated
     */
    public void setCredenceClass(String credenceClass) {
        this.credenceClass = credenceClass == null ? null : credenceClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credence_info.CREDENCE_APPEND
     *
     * @return the value of user_credence_info.CREDENCE_APPEND
     *
     * @mbg.generated
     */
    public String getCredenceAppend() {
        return credenceAppend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credence_info.CREDENCE_APPEND
     *
     * @param credenceAppend the value for user_credence_info.CREDENCE_APPEND
     *
     * @mbg.generated
     */
    public void setCredenceAppend(String credenceAppend) {
        this.credenceAppend = credenceAppend == null ? null : credenceAppend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credence_info.CREDENCE_STATUS
     *
     * @return the value of user_credence_info.CREDENCE_STATUS
     *
     * @mbg.generated
     */
    public String getCredenceStatus() {
        return credenceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credence_info.CREDENCE_STATUS
     *
     * @param credenceStatus the value for user_credence_info.CREDENCE_STATUS
     *
     * @mbg.generated
     */
    public void setCredenceStatus(String credenceStatus) {
        this.credenceStatus = credenceStatus == null ? null : credenceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uciFlowno=").append(uciFlowno);
        sb.append(", uniqueid=").append(uniqueid);
        sb.append(", loginName=").append(loginName);
        sb.append(", credenceClass=").append(credenceClass);
        sb.append(", credenceAppend=").append(credenceAppend);
        sb.append(", credenceStatus=").append(credenceStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserCredenceInfo other = (UserCredenceInfo) that;
        return (this.getUciFlowno() == null ? other.getUciFlowno() == null : this.getUciFlowno().equals(other.getUciFlowno()))
            && (this.getUniqueid() == null ? other.getUniqueid() == null : this.getUniqueid().equals(other.getUniqueid()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getCredenceClass() == null ? other.getCredenceClass() == null : this.getCredenceClass().equals(other.getCredenceClass()))
            && (this.getCredenceAppend() == null ? other.getCredenceAppend() == null : this.getCredenceAppend().equals(other.getCredenceAppend()))
            && (this.getCredenceStatus() == null ? other.getCredenceStatus() == null : this.getCredenceStatus().equals(other.getCredenceStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credence_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUciFlowno() == null) ? 0 : getUciFlowno().hashCode());
        result = prime * result + ((getUniqueid() == null) ? 0 : getUniqueid().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getCredenceClass() == null) ? 0 : getCredenceClass().hashCode());
        result = prime * result + ((getCredenceAppend() == null) ? 0 : getCredenceAppend().hashCode());
        result = prime * result + ((getCredenceStatus() == null) ? 0 : getCredenceStatus().hashCode());
        return result;
    }
}